name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        go:
          - 1.17

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/vendor"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: go test -v ./...
